name: Deploy to GoDaddy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
      
    - name: Deploy to GoDaddy
      env:
        DEPLOY_USER: gfBbqx1y=JpPe6
        DEPLOY_HOST: gbt.3cb.myftpupload.com
        DEPLOY_PASSWORD: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "Verifying build directory..."
        pwd
        ls -la dist/
        
        echo "Creating and verifying portfolio directory..."
        sshpass -p "$DEPLOY_PASSWORD" ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "
          mkdir -p portfolio
          pwd
          ls -la portfolio
        "
        
        echo "Copying files using scp..."
        cd dist
        for file in $(ls); do
          echo "Copying $file..."
          sshpass -p "$DEPLOY_PASSWORD" scp -o StrictHostKeyChecking=no -r "$file" "$DEPLOY_USER@$DEPLOY_HOST:portfolio/"
        done

        echo "Setting correct permissions..."
        sshpass -p "$DEPLOY_PASSWORD" ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "
          chmod -R 755 portfolio
          find portfolio -type f -exec chmod 644 {} \;
        "

        echo "Verifying deployed files..."
        sshpass -p "$DEPLOY_PASSWORD" ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "
          echo 'Portfolio directory contents:'
          ls -la portfolio/
          echo 'File permissions:'
          stat portfolio/index.html
          echo 'Directory structure:'
          tree portfolio/ || ls -R portfolio/
        "